return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "shortblade_vital_strike",
            tab = "Short Blade",
            tabDescription = "Short Blade skill helps one use daggers, tantos, short swords, and wakizashis effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Vital Strike",
            description = "Short blade hits have a 50% chance to critically strike, increasing the attack's Health damage by 15% before later short blade perks modify it.",
        },
        {
            id = "shortblade_close_measure",
            tab = "Short Blade",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "shortblade_vital_strike" },
            cost = 1,
            x = -260,
            y = 170,
            title = "Close Measure",
            description = "Vital Strike critical hits fortify Agility by 2 points for 5 seconds. This bonus stacks up to 5 times, and each new stack refreshes the duration.",
        },
        {
            id = "shortblade_flash_cut",
            tab = "Short Blade",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "shortblade_vital_strike" },
            cost = 1,
            x = 260,
            y = 170,
            title = "Arterial Cut",
            description = "Vital Strike critical hits apply a bleeding wound that deals 4 Health damage over 30 seconds. This bleed stacks without limit.",
        },
        {
            id = "shortblade_shadow_step",
            tab = "Short Blade",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = {},
            requiresAny = { "shortblade_close_measure", "shortblade_flash_cut" },
            cost = 1,
            x = 0,
            y = 390,
            title = "Shadow Step",
            description = "Placeholder: nimble footwork enhances short blade follow-up attacks.",
        },
        {
            id = "shortblade_master_of_knives",
            tab = "Short Blade",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "shortblade_shadow_step" },
            cost = 2,
            x = 0,
            y = 610,
            title = "Master of Knives",
            description = "Placeholder: mastery perk for the short blade tree.",
        },
    },
}
