return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "mercantile_keen_trader",
            tab = "Mercantile",
            tabDescription = "Mercantile governs buying, selling, and getting the better of every deal.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Keen Trader",
            description = "Mercantile skill progress is increased by a quarter.",
        },
        {
            id = "mercantile_regular_customer",
            tab = "Mercantile",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "mercantile_keen_trader" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Regular Customer",
            description = "Each successful barter raises the merchant's disposition by 2, up to 90.",
        },
        {
            id = "mercantile_investor",
            tab = "Mercantile",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "mercantile_regular_customer" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Investor",
            description = "While bartering with a merchant at disposition 60 or higher, you may invest 100 gold at a time, up to 500: +10 disposition permanently per 100. Up to 5 merchants.",
        },
        {
            id = "mercantile_dividends",
            tab = "Mercantile",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "mercantile_investor" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Dividends",
            description = "Invested merchants pay 10% of your investment per week, collected when you next barter with them. Collecting counts as four successful barters.",
        },
        {
            id = "mercantile_trade_prince",
            tab = "Mercantile",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "mercantile_dividends" },
            cost = 2,
            x = 0,
            y = 560,
            title = "Trade Prince",
            description = "Dividends rise to 20% per week, and you may invest up to 1000 gold in each merchant.",
        },
    },
}
