return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "armorer_careful_repairs",
            tab = "Armorer",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Careful Repairs",
            description = "Repair tools have a 15% chance to not consume a use when repairing.",
        },
        {
            id = "armorer_apprentice_hammer",
            tab = "Armorer",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = { "armorer_careful_repairs" },
            cost = 1,
            x = -80,
            y = 120,
            title = "Apprentice Hammer",
            description = "Using repair hammers and prongs lets you over-repair full condition weapons and armor to 110% condition at the cost of 5 uses.",
        },
        {
            id = "armorer_field_mender",
            tab = "Armorer",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "armorer_apprentice_hammer" },
            cost = 1,
            x = 60,
            y = 240,
            title = "Honed or Hardened",
            description = "Repair tools can temper weapons in your inventory. Hone a weapon for higher damage and lower weight at the cost of durability, or harden it for greater durability at the cost of weight and damage. Tempered weapons can be restored; unenchanted tempered weapons cannot be enchanted afterward.",
        },
        {
            id = "armorer_masterwork_rivets",
            tab = "Armorer",
            minimumSkill = 70,
            effectId = "demo_noop",
            requires = { "armorer_field_mender" },
            cost = 1,
            x = 200,
            y = 360,
            title = "Reforged Plating",
            description = "Repair tools can refit armor in your inventory. Reinforce armor to make it heavier, tougher, and more protective, or trim it to make it lighter at the cost of armor rating and durability. Reforged armor can be restored.",
        },
        {
            id = "armorer_masterwork",
            tab = "Armorer",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "armorer_masterwork_rivets" },
            cost = 1,
            x = 340,
            y = 480,
            title = "Masterwork",
            description = "Repair tools can masterwork one weapon or piece of armor in your inventory, improving damage or armor rating and durability without changing value or weight. Only one masterwork can exist at a time, and it can be restored.",
        },
    },
}
