return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "armorer_apprentice_hammer",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Apprentice Hammer",
            description = "Using repair hammers and prongs lets you over-repair full condition weapons and armor to 110% condition at the cost of 5 uses.",
        },
        {
            id = "armorer_careful_repairs",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_apprentice_hammer" },
            cost = 1,
            x = -80,
            y = 120,
            title = "Careful Repairs",
            description = "Repair tools have a 15% chance to not consume a use when repairing.",
        },
        {
            id = "armorer_field_mender",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_careful_repairs" },
            cost = 1,
            x = 60,
            y = 240,
            title = "Field Mender",
            description = "UI-only placeholder perk.",
        },
        {
            id = "armorer_masterwork_rivets",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_field_mender" },
            cost = 1,
            x = 200,
            y = 360,
            title = "Masterwork Rivets",
            description = "UI-only placeholder perk.",
        },
        {
            id = "armorer_artisans_focus",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_masterwork_rivets" },
            cost = 1,
            x = 340,
            y = 480,
            title = "Artisan's Focus",
            description = "UI-only placeholder perk.",
        },
    },
}
