return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "armorer_apprentice_hammer",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Apprentice Hammer",
            description = "Using repair hammers and prongs lets you over-repair equipped weapons and armor to 110% condition for a short window.",
        },
        {
            id = "armorer_temper_study",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_apprentice_hammer" },
            cost = 1,
            x = -80,
            y = 120,
            title = "Temper Study",
            description = "UI-only placeholder perk.",
        },
        {
            id = "armorer_field_mender",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_temper_study" },
            cost = 1,
            x = 60,
            y = 240,
            title = "Field Mender",
            description = "UI-only placeholder perk.",
        },
        {
            id = "armorer_masterwork_rivets",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_field_mender" },
            cost = 1,
            x = 200,
            y = 360,
            title = "Masterwork Rivets",
            description = "UI-only placeholder perk.",
        },
        {
            id = "armorer_artisans_focus",
            tab = "Armorer",
            effectId = "demo_noop",
            requires = { "armorer_masterwork_rivets" },
            cost = 1,
            x = 340,
            y = 480,
            title = "Artisan's Focus",
            description = "UI-only placeholder perk.",
        },
    },
}
