return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "mysticism_old_ways_initiate",
            tab = "Mysticism",
            tabDescription = "Mysticism bends the fabric of magic itself: absorbing power, binding souls, and folding the distance between places.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Old Ways Initiate",
            description = "Every Mysticism spell you cast returns a quarter of the magicka it cost you.",
        },
        {
            id = "mysticism_deep_wellspring",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Deep Wellspring",
            description = "Your reserves deepen: your maximum magicka is increased by 25.",
        },
        {
            id = "mysticism_spell_drinker",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "mysticism_old_ways_initiate" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Spell-Drinker",
            description = "When one of your Absorb spells strikes home you briefly drink in hostile magic, gaining Spell Absorption for a few seconds. Landing another Absorb refreshes the ward rather than stacking it.",
        },
        {
            id = "mysticism_paths_between",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "mysticism_deep_wellspring" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Paths Between",
            description = "The old roads open to you: Mark, Recall, Almsivi Intervention and Divine Intervention cost no magicka.",
        },
        {
            id = "mysticism_soul_siphon",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "mysticism_spell_drinker" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Soul Siphon",
            description = "Slaying a foe held by your Soultrap tears loose a rush of power, restoring magicka scaled with your Mysticism.",
        },
        {
            id = "mysticism_omniscience",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 75,
            requires = { "mysticism_paths_between" },
            cost = 2,
            x = 220,
            y = 280,
            title = "Omniscience",
            description = "Once a day, open your inner eye: nearby creatures, keys and enchantments are revealed to you for a full minute.",
        },
        {
            id = "mysticism_devour_magic",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "mysticism_soul_siphon" },
            cost = 2,
            x = -220,
            y = 420,
            title = "Devour Magic",
            description = "Once a day, open your soul wide and swallow what is cast against you: gain Spell Absorption 50 for 30 seconds.",
        },
    },
}
