return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "mysticism_old_ways_initiate",
            tab = "Mysticism",
            tabDescription = "Mysticism bends the fabric of magic itself: absorbing power, binding souls, and folding the distance between places.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Old Ways Initiate",
            description = "Mysticism spells refund a quarter of their cost.",
        },
        {
            id = "mysticism_deep_wellspring",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Deep Wellspring",
            description = "+25 maximum magicka.",
        },
        {
            id = "mysticism_spell_drinker",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "mysticism_old_ways_initiate" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Spell-Drinker",
            description = "Landing an Absorb spell grants Spell Absorption 20 for 8 seconds. Does not stack.",
        },
        {
            id = "mysticism_paths_between",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "mysticism_deep_wellspring" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Paths Between",
            description = "Mark, Recall, Almsivi Intervention and Divine Intervention cost no magicka.",
        },
        {
            id = "mysticism_soul_siphon",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "mysticism_spell_drinker" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Soul Siphon",
            description = "Killing a foe under your Soultrap restores 6 magicka per level of the foe.",
        },
        {
            id = "mysticism_omniscience",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 75,
            requires = { "mysticism_paths_between" },
            cost = 2,
            x = 220,
            y = 280,
            title = "Omniscience",
            description = "Grants a power: Detect Animal, Key and Enchantment for 60 seconds, once per day.",
        },
        {
            id = "mysticism_devour_magic",
            tab = "Mysticism",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "mysticism_soul_siphon" },
            cost = 2,
            x = -220,
            y = 420,
            title = "Devour Magic",
            description = "Grants a power: Spell Absorption 50 for 30 seconds, once per day.",
        },
    },
}
