local settings = require("scripts.SkillPerkSystem.settings")

-- Canonical built-in longblade perk source (only file for this skill).
return {
    schema = "skillperks.vNext",
    enabled = settings.ENABLE_DEMO_TREE_PERKS,
    perks = {
        {
            id = "longblade_demo_root",
            skill = "longblade",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Long Blade Fundamentals",
            description = "Core stance training for all long blade techniques.",
        },
        {
            id = "longblade_demo_precision",
            skill = "longblade",
            effectId = "demo_noop",
            requires = { "longblade_demo_root" },
            cost = 1,
            x = -180,
            y = 120,
            title = "Precision Cuts",
            description = "Improves spacing and tip-control for measured strikes.",
        },
        {
            id = "longblade_demo_pressure",
            skill = "longblade",
            effectId = "demo_noop",
            requires = { "longblade_demo_root" },
            cost = 1,
            x = 0,
            y = 120,
            title = "Pressure Rhythm",
            description = "Keeps tempo through chained attacks.",
        },
        {
            id = "longblade_demo_cleaving",
            skill = "longblade",
            effectId = "demo_noop",
            requires = { "longblade_demo_root" },
            cost = 1,
            x = 180,
            y = 120,
            title = "Cleaving Arc",
            description = "Adds broad sweeps to control space.",
        },
        {
            id = "longblade_demo_duelist",
            skill = "longblade",
            effectId = "demo_noop",
            requires = { "longblade_demo_precision" },
            cost = 1,
            x = -120,
            y = 260,
            title = "Duelist Finish",
            description = "Focused finishing sequence from precision line.",
        },
        {
            id = "longblade_demo_whirlwind",
            skill = "longblade",
            effectId = "demo_noop",
            requires = { "longblade_demo_cleaving" },
            cost = 1,
            x = 120,
            y = 260,
            title = "Whirlwind Finish",
            description = "Momentum-based finish from cleaving line.",
        },
        {
            id = "longblade_demo_mastery",
            skill = "longblade",
            effectId = "demo_noop",
            requires = { "longblade_demo_duelist", "longblade_demo_whirlwind", "longblade_demo_pressure" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Grandmaster Form",
            description = "Final chain node requiring both finishers and pressure control.",
        },
    },
}
