return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "block_hallowed_guard",
            tab = "Block",
            tabDescription = "Block skill allows one to use shields to block any melee attack. This page currently contains placeholder skeleton perks for two future block specializations.",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -360,
            y = 0,
            title = "Hallowed Guard",
            description = "Paladin tree starter. Reserved for faith-infused defensive techniques.",
        },
        {
            id = "block_aegis_rite",
            tab = "Block",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -120,
            y = 0,
            title = "Aegis Rite",
            description = "Paladin tree tier 2 placeholder. Future perk effect to be implemented and tested separately.",
        },
        {
            id = "block_bulwark_of_light",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_hallowed_guard", "block_aegis_rite" },
            cost = 1,
            x = -360,
            y = 280,
            title = "Bulwark of Light",
            description = "Paladin tree capstone placeholder. No gameplay effect yet.",
        },
        {
            id = "block_shield_fundamentals",
            tab = "Block",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 140,
            y = 0,
            title = "Shield Fundamentals",
            description = "While using a shield and a one-handed weapon or tool, gain armor equal to your Block skill / 5 (rounded down).",
        },
        {
            id = "block_guardians_habit",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_shield_fundamentals" },
            cost = 1,
            x = 140,
            y = 120,
            title = "Guardian's Habit",
            description = "Successful shield blocks restore fatigue and repair shield condition based on your Block skill.",
        },
        {
            id = "block_reactive_enchanting",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_hallowed_guard", "block_aegis_rite" },
            cost = 1,
            x = -120,
            y = 280,
            title = "Reactive Enchanting",
            description = "Successful shield blocks trigger your shield's enchantment: self effects apply to you, and touch or target effects apply to your attacker.",
        },
        {
            id = "block_steady_wall",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_guardians_habit" },
            cost = 1,
            x = 140,
            y = 240,
            title = "Guard Momentum",
            description = "Each successful shield block grants 1 stack of Guard Momentum for 5 seconds, up to 5 stacks. Each stack fortifies Block by 4 and increases Armor by 3 while using a shield.",
        },
    },
}
