return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "block_hallowed_guard",
            tab = "Block",
            tabDescription = "Block skill allows one to use shields to block any melee attack. This page currently contains placeholder skeleton perks for two future block specializations.",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -260,
            y = 0,
            title = "Hallowed Guard",
            description = "Paladin tree starter. Reserved for faith-infused defensive techniques.",
        },
        {
            id = "block_aegis_rite",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_hallowed_guard" },
            cost = 1,
            x = -260,
            y = 120,
            title = "Aegis Rite",
            description = "Paladin tree tier 2 placeholder. Future perk effect to be implemented and tested separately.",
        },
        {
            id = "block_bulwark_of_light",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_aegis_rite" },
            cost = 1,
            x = -260,
            y = 240,
            title = "Bulwark of Light",
            description = "Paladin tree capstone placeholder. No gameplay effect yet.",
        },
        {
            id = "block_shield_fundamentals",
            tab = "Block",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 260,
            y = 0,
            title = "Shield Fundamentals",
            description = "General tree starter. Reserved for practical all-around shield improvements.",
        },
        {
            id = "block_guardians_habit",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_shield_fundamentals" },
            cost = 1,
            x = 260,
            y = 120,
            title = "Guardian's Habit",
            description = "General tree tier 2 placeholder. Future perk effect to be implemented and tested separately.",
        },
        {
            id = "block_reactive_enchanting",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_guardians_habit" },
            cost = 1,
            x = 260,
            y = 240,
            title = "Reactive Enchanting",
            description = "General tree capstone placeholder for the planned enchant-on-block behavior. No gameplay effect yet.",
        },
    },
}
