return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "block_basic_guard",
            tab = "Block",
            tabDescription = "Block skill allows one to use shields to block any melee attack. A successful block removes all damage from the attack.",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Basic Guard",
            description = "Foundational shield posture. Increases confidence while blocking.",
        },
        {
            id = "block_reactive_guard",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_basic_guard" },
            cost = 1,
            x = -120,
            y = 120,
            title = "Reactive Guard",
            description = "Faster reaction windows against incoming melee attacks.",
        },
        {
            id = "block_bulwark_stance",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_basic_guard" },
            cost = 1,
            x = 120,
            y = 120,
            title = "Bulwark Stance",
            description = "A steady stance that favors sustained defense.",
        },
        {
            id = "block_iron_wall",
            tab = "Block",
            effectId = "demo_noop",
            requires = { "block_reactive_guard", "block_bulwark_stance" },
            cost = 2,
            x = 0,
            y = 260,
            title = "Iron Wall",
            description = "Late-chain defensive mastery that branches from both lines.",
        },
        {
            id = "block_arcane_bulwark",
            tab = "Block",
            minimumSkill = 20,
            effectId = "block_arcane_bulwark_effect",
            requires = {},
            cost = 1,
            x = 420,
            y = 0,
            icon = "icons/skillperks/block/arcane_bulwark.dds",
            title = "Arcane Bulwark",
            description = "Paladin branch start (azure shield icon). While actively blocking, gain modest magic resistance against hostile spells.",
        },
        {
            id = "block_warded_rebuke",
            tab = "Block",
            minimumSkill = 40,
            effectId = "block_warded_rebuke_effect",
            requires = { "block_arcane_bulwark" },
            cost = 1,
            x = 420,
            y = 140,
            icon = "icons/skillperks/block/warded_rebuke.dds",
            title = "Warded Rebuke",
            description = "Silver ward icon. Successful shield blocks grant a brief anti-magic ward that can absorb a small amount of hostile spell pressure.",
        },
        {
            id = "block_mirror_aegis",
            tab = "Block",
            minimumSkill = 60,
            effectId = "block_mirror_aegis_effect",
            requires = { "block_warded_rebuke" },
            cost = 2,
            x = 420,
            y = 280,
            icon = "icons/skillperks/block/mirror_aegis.dds",
            title = "Mirror Aegis",
            description = "Radiant mirror icon. Blocked hostile spells have a low chance to reflect part of their force back to the caster.",
        },
        {
            id = "block_guardians_pulse",
            tab = "Block",
            minimumSkill = 80,
            effectId = "block_guardians_pulse_effect",
            requires = { "block_mirror_aegis" },
            cost = 2,
            x = 420,
            y = 420,
            icon = "icons/skillperks/block/guardians_pulse.dds",
            title = "Guardian's Pulse",
            description = "Golden heart-shield icon. Timed shield blocks release a small restorative pulse with an internal cooldown.",
        },
    },
}
