return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "illusion_practiced_illusionist",
            tab = "Illusion",
            tabDescription = "Illusion bends light, sound and the mind: hiding, charming, calming and terrifying.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Practiced Illusionist",
            description = "Illusion spells refund a quarter of their cost.",
        },
        {
            id = "illusion_illusionists_reserve",
            tab = "Illusion",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Illusionist's Reserve",
            description = "+25 maximum magicka.",
        },
        {
            id = "illusion_blinding_light",
            tab = "Illusion",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "illusion_practiced_illusionist" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Blinding Light",
            description = "Blind also drains the target's Agility by half its magnitude for its duration. Does not stack.",
        },
        {
            id = "illusion_cold_fear",
            tab = "Illusion",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = {},
            requiresAny = { "illusion_practiced_illusionist", "illusion_illusionists_reserve" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Cold Fear",
            description = "Demoralize has a chance equal to half its magnitude to make the target drop their weapon.",
        },
        {
            id = "illusion_harsh_light",
            tab = "Illusion",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "illusion_illusionists_reserve" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Harsh Light",
            description = "Light also drains the Agility of nearby NPCs by a fifth of its magnitude for its duration. Does not stack.",
        },
        {
            id = "illusion_deafening_roar",
            tab = "Illusion",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "illusion_blinding_light" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Deafening Roar",
            description = "Sound also damages the target's magicka by a quarter of its magnitude per second for its duration. Does not stack.",
        },
        {
            id = "illusion_helpless",
            tab = "Illusion",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "illusion_cold_fear" },
            cost = 2,
            x = 0,
            y = 280,
            title = "Helpless",
            description = "Your attacks deal 50% more damage to paralyzed targets.",
        },
        {
            id = "illusion_fading_step",
            tab = "Illusion",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "illusion_harsh_light" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Fading Step",
            description = "Invisibility and Chameleon also grant Sanctuary (up to 20) for their duration.",
        },
    },
}
