return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "spear_point_control",
            tab = "Spear",
            tabDescription = "Spear skill helps one use spears and long thrusting weapons effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Point Control",
            description = "Placeholder: Improve basic spear handling and thrust accuracy.",
        },
        {
            id = "spear_long_guard",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "spear_point_control" },
            cost = 1,
            x = -210,
            y = 115,
            title = "Long Guard",
            description = "Placeholder: Keep enemies at bay with disciplined spear spacing.",
        },
        {
            id = "spear_driving_step",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "spear_point_control" },
            cost = 1,
            x = 120,
            y = 190,
            title = "Driving Step",
            description = "Placeholder: Convert forward movement into stronger spear thrusts.",
        },
        {
            id = "spear_hook_and_turn",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 55,
            requires = { "spear_long_guard" },
            cost = 1,
            x = -120,
            y = 305,
            title = "Hook and Turn",
            description = "Placeholder: Use the spear haft and head to disrupt an enemy's stance.",
        },
        {
            id = "spear_line_breaker",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 70,
            requires = {},
            requiresAny = { "spear_driving_step", "spear_hook_and_turn" },
            cost = 1,
            x = 210,
            y = 420,
            title = "Line Breaker",
            description = "Placeholder: Punish staggered foes with decisive spear follow-through.",
        },
        {
            id = "spear_ashlander_pike",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "spear_line_breaker" },
            cost = 2,
            x = 0,
            y = 560,
            title = "Ashlander Pike",
            description = "Placeholder: Master the spear with a capstone technique worthy of Vvardenfell's open wastes.",
        },
    },
}
