return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "spear_point_control",
            tab = "Spear",
            tabDescription = "Spear skill helps one use spears and long thrusting weapons effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Point Control",
            description = "While a spear is equipped, fortify Endurance by 5 and attacks deal 5% more Health damage.",
        },
        {
            id = "spear_long_guard",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "spear_point_control" },
            cost = 1,
            x = -210,
            y = 115,
            title = "Long Guard",
            description = "While a spear is equipped and no shield is equipped, gain Armor equal to your Spear skill / 10 (rounded down).",
        },
        {
            id = "spear_driving_step",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "spear_point_control" },
            cost = 1,
            x = 120,
            y = 190,
            title = "Driving Step",
            description = "Thrust attacks against opponents above 75% Health deal 10% more Health damage and 10 extra Fatigue damage.",
        },
        {
            id = "spear_hook_and_turn",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 55,
            requires = { "spear_long_guard" },
            cost = 1,
            x = -120,
            y = 305,
            title = "Hook and Turn",
            description = "While a spear is equipped, successful chop or slash attacks prime your next thrust within 5 seconds. The primed thrust deals 15% more Health damage and 10 extra Fatigue damage.",
        },
        {
            id = "spear_line_breaker",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 70,
            requires = {},
            requiresAny = { "spear_driving_step", "spear_hook_and_turn" },
            cost = 1,
            x = 210,
            y = 420,
            title = "Line Breaker",
            description = "Spear chop and slash attacks deal 200% more Health damage to targets below 50% Fatigue.",
        },
        {
            id = "spear_master_vanguard",
            tab = "Spear",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "spear_line_breaker" },
            cost = 2,
            x = 0,
            y = 560,
            title = "Master Vanguard",
            description = "Spear hits fortify Endurance and Agility by 5 for 10 seconds.",
        },
    },
}
