return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "unarmored_unburdened_form",
            tab = "Unarmored",
            tabDescription = "Unarmored skill helps one avoid or withstand attacks without wearing armor.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Unburdened Form",
            description = "While you have no armored cuirass, greaves, or shield equipped, gain Armor equal to your Unarmored skill / 10 (rounded down).",
        },
        {
            id = "unarmored_flowing_step",
            tab = "Unarmored",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "unarmored_unburdened_form" },
            cost = 1,
            x = -180,
            y = 140,
            title = "Flowing Step",
            description = "While you have no armor or shield equipped, fortify Agility by 5. This bonus increases to 10 while you are above 75% Fatigue.",
        },
        {
            id = "unarmored_silk_guard",
            tab = "Unarmored",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "unarmored_unburdened_form" },
            cost = 1,
            x = 180,
            y = 140,
            title = "Silk Guard",
            description = "Placeholder perk for the Unarmored tree.",
        },
        {
            id = "unarmored_empty_mail",
            tab = "Unarmored",
            effectId = "demo_noop",
            minimumSkill = 60,
            requires = { "unarmored_flowing_step", "unarmored_silk_guard" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Empty Mail",
            description = "Placeholder perk for the Unarmored tree.",
        },
        {
            id = "unarmored_master_of_motion",
            tab = "Unarmored",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "unarmored_empty_mail" },
            cost = 2,
            x = 0,
            y = 440,
            title = "Master of Motion",
            description = "Placeholder perk for the Unarmored tree.",
        },
    },
}
