return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "longblade_fundamentals",
            tab = "Long Blade",
            tabDescription = "Long Blade skill lets one use broadswords, sabers, longswords, claymores, katanas, and dai-katanas effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Long Blade Fundamentals",
            description = "While above 80% Fatigue, gain +5 Long Blade.",
        },
        {
            id = "longblade_demo_precision",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_fundamentals" },
            cost = 1,
            x = -180,
            y = 120,
            title = "Duelist's Tempo",
            description = "One-handed long blade hits reduce your target's Agility by 3 and increase yours by 3 for 4 seconds. Stacks up to 5 times; applying a stack refreshes the duration.",
        },
        {
            id = "longblade_demo_pressure",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_fundamentals" },
            cost = 1,
            x = 0,
            y = 120,
            title = "Pressure Rhythm",
            description = "Keeps tempo through chained attacks.",
        },
        {
            id = "longblade_demo_cleaving",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_fundamentals" },
            cost = 1,
            x = 180,
            y = 120,
            title = "Cleaving Arc",
            description = "Adds broad sweeps to control space.",
        },
        {
            id = "longblade_demo_duelist",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_demo_precision" },
            cost = 1,
            x = -120,
            y = 260,
            title = "Duelist Finish",
            description = "Focused finishing sequence from precision line.",
        },
        {
            id = "longblade_demo_whirlwind",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_demo_cleaving" },
            cost = 1,
            x = 120,
            y = 260,
            title = "Whirlwind Finish",
            description = "Momentum-based finish from cleaving line.",
        },
        {
            id = "longblade_demo_mastery",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_demo_duelist", "longblade_demo_whirlwind", "longblade_demo_pressure" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Grandmaster Form",
            description = "Final chain node requiring both finishers and pressure control.",
        },
    },
}
