return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "longblade_fundamentals",
            tab = "Long Blade",
            tabDescription = "Long Blade skill lets one use broadswords, sabers, longswords, claymores, katanas, and dai-katanas effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Long Blade Fundamentals",
            description = "While above 80% Fatigue, gain +5 Long Blade.",
        },
        {
            id = "longblade_demo_precision",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_fundamentals" },
            cost = 1,
            x = -180,
            y = 120,
            title = "Duelist's Tempo",
            description = "One-handed long blade hits reduce your target's Agility by 3 and increase yours by 3 for 4 seconds. Stacks up to 5 times; applying a stack refreshes the duration.",
        },
        {
            id = "longblade_keen_edge",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_fundamentals" },
            cost = 1,
            x = 0,
            y = 120,
            title = "Keen Edge",
            description = "Long blade hits have a 5% chance to deal 20 extra damage as a critical hit. This can trigger separately from Greatblade Criticals.",
        },
        {
            id = "longblade_greatblade_form",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_fundamentals" },
            cost = 1,
            x = 180,
            y = 120,
            title = "Greatblade Form",
            description = "While wielding a two-handed long blade, gain increased Attack at the cost of making enemy attacks easier to land.",
        },
        {
            id = "longblade_demo_duelist",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_demo_precision" },
            cost = 1,
            x = -120,
            y = 260,
            title = "Duelist's Form",
            description = "While wielding a one-handed long blade with no shield equipped, gain increased chance to dodge attacks and resistance to normal weapons.",
        },
        {
            id = "longblade_demo_whirlwind",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_greatblade_form" },
            cost = 1,
            x = 120,
            y = 260,
            title = "Greatblade Criticals",
            description = "Two-handed long blade hits have a 25% chance to deal 20 extra damage as a critical hit.",
        },
        {
            id = "longblade_demo_mastery",
            tab = "Long Blade",
            effectId = "demo_noop",
            requires = { "longblade_demo_duelist", "longblade_demo_whirlwind", "longblade_keen_edge" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Grandmaster Form",
            description = "Final chain node requiring both finishers and pressure control.",
        },
    },
}
