return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "lightarmor_quick_buckle",
            tab = "Light Armor",
            tabDescription = "Light Armor skill helps one stay protected while moving quickly in lighter protective gear.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -120,
            y = 0,
            title = "Fitted Harness",
            description = "While you have a Light Armor cuirass and greaves equipped, gain Armor equal to your Light Armor skill / 10 (rounded down).",
        },
        {
            id = "lightarmor_soft_landing",
            tab = "Light Armor",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "lightarmor_quick_buckle" },
            cost = 1,
            x = 120,
            y = 120,
            title = "Soft Landing",
            description = "Fortify Acrobatics by 10 while wearing Light Armor boots. Argonians and Khajiit receive this bonus from Light Armor greaves instead.",
        },
        {
            id = "lightarmor_skirmisher_stride",
            tab = "Light Armor",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "lightarmor_quick_buckle" },
            cost = 1,
            x = -240,
            y = 220,
            title = "Skirmisher Stride",
            description = "Restore 10 Fatigue when you are hit by an attack while wearing a Light Armor cuirass.",
        },
        {
            id = "lightarmor_glancing_angle",
            tab = "Light Armor",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = {},
            requiresAny = { "lightarmor_soft_landing", "lightarmor_skirmisher_stride" },
            cost = 1,
            x = 40,
            y = 340,
            title = "Glancing Angle",
            description = "While wearing a Light Armor cuirass, being hit fortifies Agility by 5 for 5 seconds, stacking up to 3 times.",
        },
        {
            id = "lightarmor_second_skin",
            tab = "Light Armor",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "lightarmor_glancing_angle" },
            cost = 2,
            x = -120,
            y = 500,
            title = "Second Skin",
            description = "Equipped Light Armor is weightless and does not affect your encumbrance.",
        },
    },
}
