return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "bluntweapon_strength_in_arms",
            tab = "Blunt Weapon",
            tabDescription = "Blunt Weapon skill helps one use maces, clubs, hammers, and staves effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Strength in Arms",
            description = "Blunt weapon hits deal +1 Health damage per 10 points of your current Strength.",
        },
        {
            id = "bluntweapon_platebreaker",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "bluntweapon_strength_in_arms" },
            cost = 1,
            x = 0,
            y = 120,
            title = "Platebreaker",
            description = "Slash attacks with blunt weapons deal 10-25 condition damage to one piece of armor equipped by the target.",
        },
        {
            id = "bluntweapon_breathstealer",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "bluntweapon_platebreaker" },
            cost = 1,
            x = 0,
            y = 240,
            title = "Breathstealer",
            description = "Thrust attacks with blunt weapons deal 20 Fatigue damage.",
        },
        {
            id = "bluntweapon_heavy_hitter",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "bluntweapon_breathstealer" },
            cost = 1,
            x = 0,
            y = 360,
            title = "Heavy Hitter",
            description = "Blocked chop attacks with blunt weapons deal 300 condition damage to the blocker's shield.",
        },
        {
            id = "bluntweapon_placeholder_guarded_stance",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "bluntweapon_heavy_hitter" },
            cost = 1,
            x = -160,
            y = 480,
            title = "Placeholder Guarded Stance",
            description = "Placeholder: Wielding a blunt weapon will grant extra armor.",
        },
        {
            id = "bluntweapon_placeholder_staggering_blow",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "bluntweapon_heavy_hitter" },
            cost = 1,
            x = 160,
            y = 480,
            title = "Staggering Blow",
            description = "Chop attacks with blunt weapons deal 50% more damage, but those chop attacks are 30% slower.",
        },
        {
            id = "bluntweapon_placeholder_iron_bell",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = {},
            requiresAny = { "bluntweapon_placeholder_guarded_stance", "bluntweapon_placeholder_staggering_blow" },
            cost = 1,
            x = 0,
            y = 600,
            title = "Placeholder Iron Bell",
            description = "Placeholder: Masterful blunt weapon impacts will combine armor damage, Fatigue damage, and defensive force.",
        },
    },
}
