return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "bluntweapon_placeholder_grip",
            tab = "Blunt Weapon",
            tabDescription = "Blunt Weapon skill helps one use maces, clubs, hammers, and staves effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Placeholder Grip",
            description = "Placeholder: Blunt weapon hits will focus on steady impact and improved control.",
        },
        {
            id = "bluntweapon_placeholder_platebreaker",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "bluntweapon_placeholder_grip" },
            cost = 1,
            x = 0,
            y = 120,
            title = "Placeholder Platebreaker",
            description = "Placeholder: Blunt weapon hits will damage enemy armor condition.",
        },
        {
            id = "bluntweapon_placeholder_breathstealer",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "bluntweapon_placeholder_platebreaker" },
            cost = 1,
            x = 0,
            y = 240,
            title = "Placeholder Breathstealer",
            description = "Placeholder: Blunt weapon hits will deal additional Fatigue damage.",
        },
        {
            id = "bluntweapon_placeholder_heavy_windup",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "bluntweapon_placeholder_breathstealer" },
            cost = 1,
            x = 0,
            y = 360,
            title = "Placeholder Heavy Windup",
            description = "Placeholder: Blunt weapon swings will be slower but hit harder.",
        },
        {
            id = "bluntweapon_placeholder_guarded_stance",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "bluntweapon_placeholder_heavy_windup" },
            cost = 1,
            x = -160,
            y = 480,
            title = "Placeholder Guarded Stance",
            description = "Placeholder: Wielding a blunt weapon will grant extra armor.",
        },
        {
            id = "bluntweapon_placeholder_staggering_blow",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "bluntweapon_placeholder_heavy_windup" },
            cost = 1,
            x = 160,
            y = 480,
            title = "Placeholder Staggering Blow",
            description = "Placeholder: Heavy blunt weapon strikes will set up a unique stagger or control effect.",
        },
        {
            id = "bluntweapon_placeholder_iron_bell",
            tab = "Blunt Weapon",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = {},
            requiresAny = { "bluntweapon_placeholder_guarded_stance", "bluntweapon_placeholder_staggering_blow" },
            cost = 1,
            x = 0,
            y = 600,
            title = "Placeholder Iron Bell",
            description = "Placeholder: Masterful blunt weapon impacts will combine armor damage, Fatigue damage, and defensive force.",
        },
    },
}
