return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "athletics_steady_pace",
            tab = "Athletics",
            tabDescription = "Athletics governs how fast you run and swim, and how well you keep going once you have started.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -180,
            y = 0,
            title = "Steady Pace",
            description = "While you carry less than half your capacity, gain +5 Athletics.",
        },
        {
            id = "athletics_deep_lungs",
            tab = "Athletics",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 180,
            y = 0,
            title = "Deep Lungs",
            description = "While your fatigue is above 60%, gain +10 Endurance.",
        },
        {
            id = "athletics_momentum",
            tab = "Athletics",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = { "athletics_steady_pace", "athletics_deep_lungs" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Momentum",
            description = "Moving without stopping builds one Stride every 2 seconds, up to 5. Each Stride grants +2 Speed. Striding stops 3 seconds after you stand still, and all Strides are lost at once.",
        },
        {
            id = "athletics_long_strider",
            tab = "Athletics",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "athletics_momentum" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Long Strider",
            description = "Momentum stacks up to 10 Strides, and each Stride also grants +1 Athletics.",
        },
        {
            id = "athletics_second_wind",
            tab = "Athletics",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "athletics_momentum" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Second Wind",
            description = "When your fatigue falls below 20%, immediately recover 25% of your maximum fatigue. Cannot occur more than once every 60 seconds.",
        },
        {
            id = "athletics_relentless",
            tab = "Athletics",
            minimumSkill = 70,
            effectId = "demo_noop",
            requires = { "athletics_long_strider", "athletics_second_wind" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Relentless",
            description = "While your fatigue is above 50%, standing still no longer costs you your Strides.",
        },
        {
            id = "athletics_peerless_conditioning",
            tab = "Athletics",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "athletics_relentless" },
            cost = 2,
            x = 0,
            y = 580,
            title = "Peerless Conditioning",
            description = "Your maximum fatigue is increased by 20%, and Second Wind recovers once every 30 seconds instead of every 60.",
        },
    },
}
