return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "alchemy_ingredient_lore",
            tab = "Alchemy",
            tabDescription = "Alchemy skill governs identifying ingredient properties and brewing potions from compatible effects.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -180,
            y = 0,
            title = "Ingredient Lore",
            description = "Eating an ingredient always activates one randomly selected effect from that ingredient, even if the effect has not been identified.",
        },
        {
            id = "alchemy_careful_measure",
            tab = "Alchemy",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 180,
            y = 0,
            title = "Careful Measure",
            description = "Failed brewing attempts sometimes preserve one of the selected ingredients.",
        },
        {
            id = "alchemy_balanced_formula",
            tab = "Alchemy",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = { "alchemy_ingredient_lore", "alchemy_careful_measure" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Dual Distillation",
            description = "With a complete set of alchemy tools, choose to brew normal potions or weapon poisons. Poisons are labeled \"Poison:\" and can be applied to your equipped weapon, causing their harmful effects on the next successful hit.",
        },
        {
            id = "alchemy_concentrated_draught",
            tab = "Alchemy",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "alchemy_balanced_formula" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Concentrated Draught",
            description = "Beneficial effects from potions you brew gain increased magnitude.",
        },
        {
            id = "alchemy_purified_toxins",
            tab = "Alchemy",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "alchemy_balanced_formula" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Lingering Toxins",
            description = "Harmful effects from weapon poisons you prepare gain increased duration.",
        },
        {
            id = "alchemy_master_distillation",
            tab = "Alchemy",
            minimumSkill = 70,
            effectId = "demo_noop",
            requires = { "alchemy_concentrated_draught", "alchemy_purified_toxins" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Master Distillation",
            description = "Brewing a potion or preparing a weapon poison has a chance to produce an additional dose.",
        },
        {
            id = "alchemy_philosophers_crucible",
            tab = "Alchemy",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "alchemy_master_distillation" },
            cost = 2,
            x = 0,
            y = 580,
            title = "Philosopher's Crucible",
            description = "Potions you brew suppress harmful effects and retain beneficial effects longer, while weapon poisons suppress beneficial effects and retain harmful effects longer.",
        },
    },
}
