return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "alchemy_ingredient_lore",
            tab = "Alchemy",
            tabDescription = "Alchemy skill governs identifying ingredient properties and brewing potions from compatible effects.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -180,
            y = 0,
            title = "Ingredient Lore",
            description = "Placeholder: Eating an ingredient reveals its next unknown alchemical effect.",
        },
        {
            id = "alchemy_careful_measure",
            tab = "Alchemy",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 180,
            y = 0,
            title = "Careful Measure",
            description = "Placeholder: Failed brewing attempts sometimes preserve one of their ingredients.",
        },
        {
            id = "alchemy_balanced_formula",
            tab = "Alchemy",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = { "alchemy_ingredient_lore", "alchemy_careful_measure" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Balanced Formula",
            description = "Placeholder: Potions brewed with a complete apparatus have more consistent magnitudes and durations.",
        },
        {
            id = "alchemy_concentrated_draught",
            tab = "Alchemy",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "alchemy_balanced_formula" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Concentrated Draught",
            description = "Placeholder: Beneficial potions you brew gain increased magnitude.",
        },
        {
            id = "alchemy_purified_toxins",
            tab = "Alchemy",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "alchemy_balanced_formula" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Purified Toxins",
            description = "Placeholder: Harmful potions you brew gain increased duration.",
        },
        {
            id = "alchemy_master_distillation",
            tab = "Alchemy",
            minimumSkill = 70,
            effectId = "demo_noop",
            requires = { "alchemy_concentrated_draught", "alchemy_purified_toxins" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Master Distillation",
            description = "Placeholder: Brewing a potion has a chance to produce an additional dose.",
        },
        {
            id = "alchemy_philosophers_crucible",
            tab = "Alchemy",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "alchemy_master_distillation" },
            cost = 2,
            x = 0,
            y = 580,
            title = "Philosopher's Crucible",
            description = "Placeholder: Master-crafted potions retain their beneficial effects longer and suppress unwanted side effects.",
        },
    },
}
