return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "alteration_practiced_shaper",
            tab = "Alteration",
            tabDescription = "Alteration reshapes the physical world: locks and burdens, water and air, and the body's own resilience.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Practiced Shaper",
            description = "Every Alteration spell you cast returns a quarter of the magicka it cost you.",
        },
        {
            id = "alteration_shapers_reserve",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Shaper's Reserve",
            description = "You hold more power in reserve: your maximum magicka is increased by 25.",
        },
        {
            id = "alteration_crushing_burden",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "alteration_practiced_shaper" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Crushing Burden",
            description = "Your Burden spells also slow the target, the heavier the burden the more, for as long as it holds. A second burden replaces the first rather than stacking.",
        },
        {
            id = "alteration_retaliating_ward",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = {},
            requiresAny = { "alteration_practiced_shaper", "alteration_shapers_reserve" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Retaliating Ward",
            description = "While a Fire, Frost or Lightning Shield is on you, anyone who strikes you in melee is burned, frozen or shocked for a third of the shield's strength, at least 5.",
        },
        {
            id = "alteration_long_stride",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "alteration_shapers_reserve" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Long Stride",
            description = "Your Jump spells also fortify your Acrobatics by half their strength while they last, so you leap higher and land softer.",
        },
        {
            id = "alteration_grinding_weight",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "alteration_crushing_burden" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Grinding Weight",
            description = "A target under your Burden also bleeds fatigue every second while it holds, until they can barely swing or stand.",
        },
        {
            id = "alteration_bastion",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "alteration_retaliating_ward" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Bastion",
            description = "While a Shield spell is on you, anyone who strikes you in melee is briefly slowed.",
        },
        {
            id = "alteration_tidal_stride",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "alteration_long_stride" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Tidal Stride",
            description = "Your Swift Swim spells also fortify your Speed by a quarter of their strength, and Water Walking by 10, for as long as they last.",
        },
        {
            id = "alteration_elemental_aegis",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "alteration_retaliating_ward" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Elemental Aegis",
            description = "While a Fire, Frost or Lightning Shield is on you, anyone who strikes you in melee is left weak to that element for several seconds.",
        },
    },
}
