return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "alteration_practiced_shaper",
            tab = "Alteration",
            tabDescription = "Alteration reshapes the physical world: locks and burdens, water and air, and the body's own resilience.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Practiced Shaper",
            description = "Alteration spells refund a quarter of their cost.",
        },
        {
            id = "alteration_shapers_reserve",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Shaper's Reserve",
            description = "+25 maximum magicka.",
        },
        {
            id = "alteration_crushing_burden",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "alteration_practiced_shaper" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Crushing Burden",
            description = "Burden also drains the target's Speed by half the burden's magnitude for its duration. Does not stack.",
        },
        {
            id = "alteration_retaliating_ward",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = {},
            requiresAny = { "alteration_practiced_shaper", "alteration_shapers_reserve" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Retaliating Ward",
            description = "While an elemental Shield is active, melee attackers take that element's damage equal to a third of the shield's magnitude, minimum 5.",
        },
        {
            id = "alteration_long_stride",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "alteration_shapers_reserve" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Long Stride",
            description = "Jump spells also fortify Acrobatics by half their magnitude for their duration.",
        },
        {
            id = "alteration_grinding_weight",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "alteration_crushing_burden" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Grinding Weight",
            description = "Burden also damages the target's fatigue by a tenth of its magnitude per second for its duration. Does not stack.",
        },
        {
            id = "alteration_bastion",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "alteration_retaliating_ward" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Bastion",
            description = "While a Shield spell is active, melee attackers are slowed by 15 for 5 seconds.",
        },
        {
            id = "alteration_tidal_stride",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "alteration_long_stride" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Tidal Stride",
            description = "Swift Swim fortifies Speed by a quarter of its magnitude, and Water Walking by 10, for their duration.",
        },
        {
            id = "alteration_elemental_aegis",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "alteration_retaliating_ward" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Elemental Aegis",
            description = "While an elemental Shield is active, melee attackers gain Weakness to that element 25 for 6 seconds.",
        },
        {
            -- Hidden: High Elf, Alteration major, Illusion or Mysticism major or minor.
            id = "alteration_arcane_momentum",
            tab = "Alteration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Arcane Momentum",
            description = "Each spell cast within 4 seconds of the previous one refunds 5% more of its cost than the last, up to 25%. Any school.",
            hiddenUnless = {
                race = "high elf",
                majorSkills = { "alteration" },
                classSkillsAny = { "illusion", "mysticism" },
                label = "High Elf with Alteration as a major skill and Illusion or Mysticism as a class skill",
            },
        },
    },
}
