return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "restoration_practiced_healer",
            tab = "Restoration",
            tabDescription = "Restoration mends flesh and fortifies the body against poison, disease and harm.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Practiced Healer",
            description = "Restoration spells refund a quarter of their cost.",
        },
        {
            id = "restoration_healers_reserve",
            tab = "Restoration",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Healer's Reserve",
            description = "+25 maximum magicka.",
        },
        {
            id = "restoration_overflow",
            tab = "Restoration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "restoration_practiced_healer" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Overflow",
            description = "Restore Health cast at full health becomes an overheal pool (up to half your maximum health) that absorbs damage for 30 seconds.",
        },
        {
            id = "restoration_purifying_touch",
            tab = "Restoration",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "restoration_healers_reserve" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Purifying Touch",
            description = "Cure Poison, Cure Common Disease and Cure Blight Disease also grant the matching Resist 50 for 2 minutes.",
        },
        {
            id = "restoration_desperate_prayer",
            tab = "Restoration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "restoration_overflow" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Desperate Prayer",
            description = "Restore Health cast below a quarter health heals twice as much.",
        },
        {
            id = "restoration_bulwark_of_faith",
            tab = "Restoration",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "restoration_purifying_touch" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Bulwark of Faith",
            description = "While taking fire damage under a Fire Shield, restore 2 health per second; frost under a Frost Shield, 5 fatigue per second; shock under a Lightning Shield, 2 health and 2 fatigue per second.",
        },
        {
            id = "restoration_righteous_strike",
            tab = "Restoration",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = {},
            requiresAny = { "restoration_desperate_prayer", "restoration_bulwark_of_faith" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Righteous Strike",
            description = "While a Fortify Attack effect is active, your attacks deal 20% more damage.",
        },
    },
}
