return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "axe_kindling_grip",
            tab = "Axe",
            tabDescription = "Axe skill helps one use axes, war axes, battle axes, and halberds effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Headsman's Mark",
            description = "Axe hits deal 10% more damage to targets below 50% Health.",
        },
        {
            id = "axe_bloodletter",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "axe_kindling_grip" },
            cost = 1,
            x = -170,
            y = 115,
            title = "Bloodletter",
            description = "Axe hits make the target bleed for 1 Health per second for 5 seconds. This effect refreshes but does not stack.",
        },
        {
            id = "axe_crescent_hook",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "axe_kindling_grip" },
            cost = 1,
            x = 170,
            y = 115,
            title = "Executioner's Mercy",
            description = "Axe hits deal an additional 10% damage to targets below 50% Health.",
        },
        {
            id = "axe_splinter_waltz",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 45,
            requires = { "axe_bloodletter" },
            cost = 1,
            x = -255,
            y = 245,
            title = "Splinter Waltz",
            description = "Placeholder perk: three steps, one chop, and a tidy shower of imaginary splinters.",
        },
        {
            id = "axe_hewer_heart",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 45,
            requires = { "axe_bloodletter", "axe_crescent_hook" },
            cost = 1,
            x = 0,
            y = 245,
            title = "Hewer's Heart",
            description = "Placeholder perk: steady hands, steady breath, and a chest full of sawdust courage.",
        },
        {
            id = "axe_iron_canopy",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 45,
            requires = { "axe_crescent_hook" },
            cost = 1,
            x = 255,
            y = 245,
            title = "Iron Canopy",
            description = "Placeholder perk: raise the blade high enough and even bad luck has to duck.",
        },
        {
            id = "axe_stump_speaker",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "axe_splinter_waltz", "axe_hewer_heart" },
            cost = 1,
            x = -85,
            y = 375,
            title = "Stump Speaker",
            description = "Placeholder perk: old roots whisper where the next blow should fall.",
        },
        {
            id = "axe_fellstar_crown",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = {},
            requiresAny = { "axe_stump_speaker", "axe_iron_canopy" },
            cost = 2,
            x = 85,
            y = 505,
            title = "Fellstar Crown",
            description = "Placeholder perk: the final cut is only penciled in, but it already looks dramatic.",
        },
    },
}
