return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "axe_kindling_grip",
            tab = "Axe",
            tabDescription = "Axe skill helps one use axes, war axes, battle axes, and halberds effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Headsman's Mark",
            description = "Axe hits deal 10% more damage to targets below 50% Health.",
        },
        {
            id = "axe_bloodletter",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "axe_kindling_grip" },
            cost = 1,
            x = -170,
            y = 115,
            title = "Bloodletter",
            description = "Axe hits make the target bleed for 1 Health per second for 5 seconds. This effect refreshes but does not stack.",
        },
        {
            id = "axe_crescent_hook",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "axe_kindling_grip" },
            cost = 1,
            x = 170,
            y = 115,
            title = "Executioner's Mercy",
            description = "Axe hits deal an additional 10% damage to targets below 50% Health.",
        },
        {
            id = "axe_dragging_wound",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 45,
            requires = { "axe_bloodletter" },
            cost = 1,
            x = -255,
            y = 245,
            title = "Dragging Wound",
            description = "Bloodletter bleeds from axe hits deal the same total damage over 10 seconds instead of 5, reducing the target's Speed by 20 while they bleed.",
        },
        {
            id = "axe_hewer_heart",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 45,
            requires = {},
            requiresAny = { "axe_bloodletter", "axe_crescent_hook" },
            cost = 1,
            x = 0,
            y = 245,
            title = "Carrion Pulse",
            description = "Axe hits against targets below 50% Health apply a separate bleed stack that deals 1 Health per second for 5 seconds. This effect refreshes but does not stack.",
        },
        {
            id = "axe_iron_canopy",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 45,
            requires = { "axe_crescent_hook" },
            cost = 1,
            x = 255,
            y = 245,
            title = "Iron Canopy",
            description = "Placeholder perk: raise the blade high enough and even bad luck has to duck.",
        },
        {
            id = "axe_crimson_cleave",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = {},
            requiresAny = { "axe_dragging_wound", "axe_hewer_heart" },
            cost = 1,
            x = -85,
            y = 375,
            title = "Crimson Cleave",
            description = "Axe bleeds deal twice as much damage.",
        },
        {
            id = "axe_fellstar_crown",
            tab = "Axe",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = {},
            requiresAny = { "axe_crimson_cleave", "axe_iron_canopy" },
            cost = 2,
            x = 85,
            y = 505,
            title = "Fellstar Crown",
            description = "Placeholder perk: the final cut is only penciled in, but it already looks dramatic.",
        },
    },
}
