return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "sneak_soft_boots",
            tab = "Sneak",
            tabDescription = "Sneak governs moving unseen and unheard, and rewards travelling light and dark.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -180,
            y = 0,
            title = "Soft Boots",
            description = "While you carry less than a third of your capacity, gain +10 Sneak.",
        },
        {
            id = "sneak_patient_shadow",
            tab = "Sneak",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 180,
            y = 0,
            title = "Patient Shadow",
            description = "While sneaking and holding still, gain +10 Sneak.",
        },
        {
            id = "sneak_killers_instinct",
            tab = "Sneak",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = { "sneak_soft_boots" },
            cost = 1,
            x = -420,
            y = 140,
            title = "Killer's Instinct",
            description = "Melee attacks you land while sneaking deal 25% more damage.",
        },
        {
            id = "sneak_knife_in_the_dark",
            tab = "Sneak",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "sneak_killers_instinct" },
            cost = 1,
            x = -560,
            y = 280,
            title = "Knife in the Dark",
            description = "Sneaking attacks made with a short blade deal a further 50% more damage.",
        },
        {
            id = "sneak_light_fingers",
            tab = "Sneak",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "sneak_killers_instinct" },
            cost = 1,
            x = -420,
            y = 420,
            title = "Light Fingers",
            description = "While sneaking, gain a further +15 Sneak. Sneak governs pickpocketing, so marks part with their goods far more readily.",
        },
        {
            id = "sneak_moonless_night",
            tab = "Sneak",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = { "sneak_soft_boots", "sneak_patient_shadow" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Moonless Night",
            description = "While sneaking with no light source in hand, gain +15 Sneak and +5 Agility.",
        },
        {
            id = "sneak_cutpurse_poise",
            tab = "Sneak",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "sneak_moonless_night" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Cutpurse's Poise",
            description = "While sneaking, gain +10 Security and +10 Agility.",
        },
        {
            id = "sneak_feather_tread",
            tab = "Sneak",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "sneak_moonless_night" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Feather Tread",
            description = "While sneaking, gain +15 Speed.",
        },
        {
            id = "sneak_ghostwalk",
            tab = "Sneak",
            minimumSkill = 70,
            effectId = "demo_noop",
            requires = { "sneak_cutpurse_poise", "sneak_feather_tread" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Ghostwalk",
            description = "While sneaking, the Sneak bonuses granted by this tree are increased by half again.",
        },
        {
            id = "sneak_one_with_shadow",
            tab = "Sneak",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "sneak_ghostwalk" },
            cost = 2,
            x = 0,
            y = 580,
            title = "One With Shadow",
            description = "While sneaking with no light source in hand and carrying less than a third of your capacity, gain a further +25 Sneak, +10 Agility and +10 Speed.",
        },
    },
}
