return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "conjuration_ancestral_pact",
            tab = "Conjuration",
            tabDescription = "Conjuration governs summoning servants from Oblivion and beyond, binding spectral arms and armor, and drawing on the reserves that make such callings possible.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Ancestral Pact",
            description = "Grants a power: call an Ancestral Ghost to serve you for 60 seconds, once per day.",
        },
        {
            id = "conjuration_daedric_pact",
            tab = "Conjuration",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Daedric Pact",
            description = "Grants a power: call a Scamp to serve you for 60 seconds, once per day.",
        },
        {
            id = "conjuration_spectral_edge",
            tab = "Conjuration",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Spectral Edge",
            description = "While wielding a bound weapon, gain +15 to its weapon skill.",
        },
        {
            id = "conjuration_deepened_pact",
            tab = "Conjuration",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Deepened Pact",
            description = "Your pacts summon a Bonewalker or Clannfear for 120 seconds.",
        },
        {
            id = "conjuration_soul_tether",
            tab = "Conjuration",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Soul Tether",
            description = "+30 maximum magicka.",
        },
        {
            id = "conjuration_spectral_ward",
            tab = "Conjuration",
            minimumSkill = 65,
            effectId = "demo_noop",
            requires = { "conjuration_spectral_edge" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Spectral Ward",
            description = "Sanctuary 10 while wearing bound armor.",
        },
        {
            id = "conjuration_greater_pact",
            tab = "Conjuration",
            minimumSkill = 75,
            effectId = "demo_noop",
            requires = { "conjuration_deepened_pact" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Greater Pact",
            description = "Your pacts summon a Bonelord or Dremora for 180 seconds.",
        },
        {
            id = "conjuration_soul_reclamation",
            tab = "Conjuration",
            minimumSkill = 65,
            effectId = "demo_noop",
            requires = { "conjuration_soul_tether" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Soul Reclamation",
            description = "While below half magicka and near one of your summons, recover 1% of maximum magicka per second.",
        },
        {
            id = "conjuration_grand_conjurer",
            tab = "Conjuration",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "conjuration_greater_pact" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Grand Conjurer",
            description = "Conjuration spells refund a quarter of their cost.",
        },
    },
}
