return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "conjuration_ancestral_pact",
            tab = "Conjuration",
            tabDescription = "Conjuration governs summoning servants from Oblivion and beyond, binding spectral arms and armor, and bending creatures to your will.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Ancestral Pact",
            description = "Grants a power: call an Ancestral Ghost to serve you for 60 seconds, once per day.",
        },
        {
            id = "conjuration_daedric_pact",
            tab = "Conjuration",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Daedric Pact",
            description = "Grants a power: call a Scamp to serve you for 60 seconds, once per day.",
        },
        {
            id = "conjuration_spectral_edge",
            tab = "Conjuration",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Spectral Edge",
            description = "While wielding a bound weapon, gain +15 to its weapon skill.",
        },
        {
            id = "conjuration_deepened_pact",
            tab = "Conjuration",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Deepened Pact",
            description = "Your pact powers call stronger servants for longer: a Bonewalker or a Clannfear, for 120 seconds.",
        },
        {
            id = "conjuration_voice_of_dominion",
            tab = "Conjuration",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Beast Tongue",
            description = "Grants a spell that cows a lesser beast into serving you briefly. Stronger creatures ignore it.",
        },
        {
            id = "conjuration_spectral_ward",
            tab = "Conjuration",
            minimumSkill = 65,
            effectId = "demo_noop",
            requires = { "conjuration_spectral_edge" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Spectral Ward",
            description = "While wearing any piece of bound armor, you are harder to strike (Sanctuary 10).",
        },
        {
            id = "conjuration_greater_pact",
            tab = "Conjuration",
            minimumSkill = 75,
            effectId = "demo_noop",
            requires = { "conjuration_deepened_pact" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Greater Pact",
            description = "Your pact powers call mighty servants: a Bonelord or a Dremora, for 180 seconds.",
        },
        {
            id = "conjuration_rebuke_the_dead",
            tab = "Conjuration",
            minimumSkill = 65,
            effectId = "demo_noop",
            requires = { "conjuration_voice_of_dominion" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Rebuke the Dead",
            description = "Grants a spell that drives back the walking dead around you, and lets Beast Tongue hold larger beasts for longer.",
        },
        {
            id = "conjuration_grand_conjurer",
            tab = "Conjuration",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "conjuration_greater_pact" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Grand Conjurer",
            description = "Casting Conjuration spells restores a portion of your magicka.",
        },
    },
}
