return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "conjuration_ancestral_pact",
            tab = "Conjuration",
            tabDescription = "Conjuration governs summoning servants from Oblivion and beyond, binding spectral arms and armor, and drawing on the reserves that make such callings possible.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Ancestral Pact",
            description = "Grants a power: call an Ancestral Ghost to serve you for 60 seconds, once per day.",
        },
        {
            id = "conjuration_daedric_pact",
            tab = "Conjuration",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Daedric Pact",
            description = "Grants a power: call a Scamp to serve you for 60 seconds, once per day.",
        },
        {
            id = "conjuration_spectral_edge",
            tab = "Conjuration",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Spectral Edge",
            description = "While wielding a bound weapon, gain +15 to its weapon skill.",
        },
        {
            id = "conjuration_deepened_pact",
            tab = "Conjuration",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Deepened Pact",
            description = "Every pact you have formed calls a stronger servant for longer: a Bonewalker or a Clannfear, for 120 seconds. A pact formed later is bound at your current mastery.",
        },
        {
            id = "conjuration_soul_tether",
            tab = "Conjuration",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = {},
            requiresAny = { "conjuration_ancestral_pact", "conjuration_daedric_pact" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Soul Tether",
            description = "The channels you have opened hold more power: your maximum magicka is increased by 30.",
        },
        {
            id = "conjuration_spectral_ward",
            tab = "Conjuration",
            minimumSkill = 65,
            effectId = "demo_noop",
            requires = { "conjuration_spectral_edge" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Spectral Ward",
            description = "While wearing any piece of bound armor, you are harder to strike (Sanctuary 10).",
        },
        {
            id = "conjuration_greater_pact",
            tab = "Conjuration",
            minimumSkill = 75,
            effectId = "demo_noop",
            requires = { "conjuration_deepened_pact" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Greater Pact",
            description = "Every pact you have formed calls a mighty servant: a Bonelord or a Dremora, for 180 seconds. A pact formed later is bound at your current mastery.",
        },
        {
            id = "conjuration_soul_reclamation",
            tab = "Conjuration",
            minimumSkill = 65,
            effectId = "demo_noop",
            requires = { "conjuration_soul_tether" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Soul Reclamation",
            description = "When a servant you summoned is destroyed, the power binding it returns to you: restore 15 magicka. A servant that simply returns home when its time runs out gives nothing back.",
        },
        {
            id = "conjuration_grand_conjurer",
            tab = "Conjuration",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "conjuration_greater_pact" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Grand Conjurer",
            description = "Every Conjuration spell you cast returns 10% of your maximum magicka.",
        },
    },
}
