return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "handtohand_centered_stance",
            tab = "Hand-to-hand",
            tabDescription = "Hand-to-hand skill allows one to fight effectively without weapons, damaging Fatigue before Health.",
            skillId = "handtohand",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Centered Stance",
            description = "While you have no weapons or shields equipped, fortify Agility, Endurance, and Willpower by 3 points each.",
        },
        {
            id = "handtohand_open_palm",
            tab = "Hand-to-hand",
            skillId = "handtohand",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "handtohand_centered_stance" },
            cost = 1,
            x = -180,
            y = 140,
            title = "Open Palm",
            description = "Hand-to-hand hits fortify Hand-to-hand by 3 for 6 seconds, stacking up to 5 times. Gaining a stack refreshes all Open Palm stacks.",
        },
        {
            id = "handtohand_iron_knuckles",
            tab = "Hand-to-hand",
            skillId = "handtohand",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "handtohand_centered_stance" },
            cost = 1,
            x = 180,
            y = 140,
            title = "Iron Knuckles",
            description = "Hand-to-hand hits deal bonus Health damage equal to your current Fatigue divided by 30.",
        },
        {
            id = "handtohand_flowing_counter",
            tab = "Hand-to-hand",
            skillId = "handtohand",
            effectId = "demo_noop",
            minimumSkill = 60,
            requires = { "handtohand_open_palm" },
            cost = 1,
            x = -180,
            y = 280,
            title = "Way of the Bound Fist",
            description = "While both glove slots match, your hand-to-hand style changes: bare or clothing-covered hands gain Deflecting Palm; two light gauntlets deal 10-20 Magicka damage; two medium gauntlets deal 1-5 extra Health damage; two heavy gauntlets lower Agility by 10 and slow hand-to-hand attacks by 20%, but deal 5-10 extra Health damage.",
        },
        {
            id = "handtohand_empty_body_mastery",
            tab = "Hand-to-hand",
            skillId = "handtohand",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "handtohand_flowing_counter" },
            cost = 2,
            x = -180,
            y = 440,
            title = "Empty Body Mastery",
            description = "Placeholder capstone perk: reserves the defensive mastery endpoint of the Hand-to-hand tree.",
        },
        {
            id = "handtohand_breaking_fist",
            tab = "Hand-to-hand",
            skillId = "handtohand",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "handtohand_iron_knuckles" },
            cost = 2,
            x = 180,
            y = 440,
            title = "Breaking Fist",
            description = "Hand-to-hand hits deal 50% less Fatigue damage, but deal 5 to 15 bonus Health damage.",
        },
    },
}
