return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "security_steady_hands",
            tab = "Security",
            tabDescription = "Security skill allows one to open locked doors and containers with lockpicks and disarm traps with probes.",
            minimumSkill = 10,
            effectId = "security_steady_hands_effect",
            requires = {},
            cost = 1,
            x = -120,
            y = 0,
            title = "Steady Hands",
            description = "Lockpick and probe uses have a 15% chance to not be consumed.",
        },
        {
            id = "security_tumbler_sense",
            tab = "Security",
            minimumSkill = 10,
            effectId = "security_tumbler_sense_effect",
            requires = {},
            cost = 1,
            x = 120,
            y = 0,
            title = "Tumbler Sense",
            description = "Starts at 1 stack (+1 Security). Failed lockpick attempts grant +1 Security per stack (max 5) with a shared 10s decay timer.",
        },
        {
            id = "security_treasure_sense",
            tab = "Security",
            minimumSkill = 30,
            effectId = "security_treasure_sense_effect",
            requires = { "security_steady_hands" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Treasure Sense",
            description = "Chests you open will always have extra gold based on your Luck.",
        },
        {
            id = "security_quick_pick",
            tab = "Security",
            minimumSkill = 30,
            effectId = "security_quick_pick_effect",
            requires = { "security_tumbler_sense" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Quick Pick",
            description = "Lockpick and probe actions are 75% faster.",
        },
        {
            id = "security_lucky_find",
            tab = "Security",
            minimumSkill = 45,
            effectId = "security_lucky_find_effect",
            requires = { "security_treasure_sense" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Lucky Find",
            description = "On first-time container checks, there is a small chance to find a Lucky Coin. Each Lucky Coin carried grants +1 Luck.",
        },
        {
            id = "security_fortunes_habit",
            tab = "Security",
            minimumSkill = 60,
            effectId = "security_fortunes_habit_effect",
            requires = { "security_lucky_find" },
            cost = 2,
            x = -130,
            y = 420,
            title = "Fortune's Habit",
            description = "Lucky Find chance rises. Treasure Sense scales with Luck faster and grants 10% more bonus gold.",
        },
        {
            id = "security_perfect_pressure",
            tab = "Security",
            minimumSkill = 60,
            effectId = "security_perfect_pressure_effect",
            requires = {},
            requiresAny = { "security_tumbler_sense", "security_quick_pick" },
            cost = 2,
            x = 130,
            y = 420,
            title = "Perfect Pressure",
            description = "Tumbler Sense gains +2 Security per failed attempt and can fortify Security up to +10.",
        },
        {
            id = "security_unseen_hand",
            tab = "Security",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "security_fortunes_habit", "security_perfect_pressure" },
            cost = 3,
            x = 0,
            y = 560,
            title = "Unseen Hand",
            description = "Daily master technique: open a key lock or pull a random treasure cache.",
        },
    },
}
