return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "security_steady_hands",
            tab = "Security",
            tabDescription = "Security skill allows one to open locked doors and containers with lockpicks and disarm traps with probes.",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -90,
            y = 0,
            title = "Steady Hands",
            description = "Measured tool control that reduces lockpick and probe wear.",
        },
        {
            id = "security_tumbler_sense",
            tab = "Security",
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 90,
            y = 0,
            title = "Tumbler Sense",
            description = "Failed attempts briefly improve your next lockpick chances.",
        },
        {
            id = "security_treasure_sense",
            tab = "Security",
            effectId = "demo_noop",
            requires = { "security_steady_hands" },
            cost = 1,
            x = -180,
            y = 130,
            title = "Treasure Sense",
            description = "First checks on chests can reveal extra hidden gold based on Luck.",
        },
        {
            id = "security_quick_pick",
            tab = "Security",
            effectId = "demo_noop",
            requires = { "security_tumbler_sense" },
            cost = 1,
            x = 180,
            y = 130,
            title = "Quick Pick",
            description = "A practiced rhythm that speeds lockpick attempts.",
        },
        {
            id = "security_lucky_find",
            tab = "Security",
            effectId = "demo_noop",
            requires = { "security_treasure_sense" },
            cost = 1,
            x = -180,
            y = 260,
            title = "Lucky Find",
            description = "Rarely discover Lucky Coins in containers during first-time checks.",
        },
        {
            id = "security_fortunes_habit",
            tab = "Security",
            effectId = "demo_noop",
            requires = { "security_treasure_sense", "security_lucky_find" },
            cost = 2,
            x = -60,
            y = 390,
            title = "Fortune's Habit",
            description = "Treasure routines improve chest windfalls and valuable finds.",
        },
        {
            id = "security_perfect_pressure",
            tab = "Security",
            effectId = "demo_noop",
            requires = { "security_tumbler_sense", "security_quick_pick" },
            cost = 2,
            x = 60,
            y = 390,
            title = "Perfect Pressure",
            description = "Refined touch makes tumbler momentum easier to maintain.",
        },
        {
            id = "security_unseen_hand",
            tab = "Security",
            effectId = "demo_noop",
            requires = { "security_fortunes_habit", "security_perfect_pressure" },
            cost = 3,
            x = 0,
            y = 530,
            title = "Unseen Hand",
            description = "Daily master technique: open a key lock or pull a random treasure cache.",
        },
    },
}
