return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "destruction_elemental_focus",
            tab = "Destruction",
            tabDescription = "Destruction governs spells that burn, freeze, shock, corrode, and sap the life from what they touch.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Elemental Focus",
            description = "+10 Destruction while above half magicka.",
        },
        {
            id = "destruction_arcane_reservoir",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Arcane Reservoir",
            description = "+25 maximum magicka.",
        },
        {
            id = "destruction_searing_heat",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Searing Heat",
            description = "Fire damage also burns the target for half the damage over 6 seconds.",
        },
        {
            id = "destruction_biting_cold",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Biting Cold",
            description = "Frost damage also drains the target's Speed by 15 for 8 seconds.",
        },
        {
            id = "destruction_storm_channel",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Storm Channel",
            description = "Shock damage also damages the target's magicka by half the damage dealt.",
        },
        {
            id = "destruction_sundering_ruin",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = {},
            requiresAny = { "destruction_searing_heat", "destruction_biting_cold", "destruction_storm_channel" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Sundering Ruin",
            description = "Disintegrate Armor drains the target's skill with their worn armor, and Disintegrate Weapon their skill with their held weapon, by a quarter of your Destruction. Does not stack.",
        },
        {
            id = "destruction_withering_curse",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = {},
            requiresAny = { "destruction_searing_heat", "destruction_biting_cold", "destruction_storm_channel" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Withering Curse",
            description = "Drain Health, Fatigue and Magicka spells fortify your matching maximum by the drained amount for the drain's duration. Does not stack.",
        },
        {
            id = "destruction_efficient_ruin",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "destruction_arcane_reservoir" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Efficient Ruin",
            description = "Destruction spells refund a quarter of their cost.",
        },
        {
            id = "destruction_annihilation_mastery",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "destruction_efficient_ruin" },
            cost = 2,
            x = 0,
            y = 560,
            title = "Annihilation Mastery",
            description = "Elemental damage also applies Weakness to that element, 10 for 8 seconds. Stacks.",
        },
        {
            -- Hidden: Dark Elf, Destruction major, Mysticism major or minor.
            id = "destruction_ashborn",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 60,
            requires = {},
            cost = 1,
            x = -220,
            y = 560,
            title = "Ashborn",
            description = "A target killed within 4 seconds of your fire damage landing restores 4 magicka per level of the target.",
            hiddenUnless = {
                race = "dark elf",
                majorSkills = { "destruction" },
                classSkills = { "mysticism" },
                label = "Dark Elf with Destruction as a major skill and Mysticism as a class skill",
            },
        },
    },
}
