return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "destruction_elemental_focus",
            tab = "Destruction",
            tabDescription = "Destruction governs spells that burn, freeze, shock, corrode, and sap the life from what they touch.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Elemental Focus",
            description = "Your command of the elements sharpens: gain +10 Destruction.",
        },
        {
            id = "destruction_arcane_reservoir",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Arcane Reservoir",
            description = "You hold more power in reserve: your maximum magicka is increased by 25.",
        },
        {
            id = "destruction_searing_heat",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Searing Heat",
            description = "Your fire damage leaves the target burning, dealing further fire damage over several seconds.",
        },
        {
            id = "destruction_biting_cold",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Biting Cold",
            description = "Your frost damage leaves the target sluggish, slowing them for several seconds.",
        },
        {
            id = "destruction_storm_channel",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Storm Channel",
            description = "Your shock damage burns away the target's magicka, half as much as the health it took.",
        },
        {
            id = "destruction_sundering_ruin",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = {},
            requiresAny = { "destruction_searing_heat", "destruction_biting_cold", "destruction_storm_channel" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Sundering Ruin",
            description = "Disintegrate Armor also saps the target's skill with the armor they wear, and Disintegrate Weapon their skill with the weapon they hold, leaving them easier to hit and easier to dodge.",
        },
        {
            id = "destruction_withering_curse",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = {},
            requiresAny = { "destruction_searing_heat", "destruction_biting_cold", "destruction_storm_channel" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Withering Curse",
            description = "What your Drain spells take, you keep. Drained health, fatigue and magicka flow into you, and a drained attribute or skill fortifies your own for as long as the curse holds.",
        },
        {
            id = "destruction_efficient_ruin",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "destruction_arcane_reservoir" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Efficient Ruin",
            description = "Every Destruction spell you cast returns a quarter of the magicka it cost you.",
        },
        {
            id = "destruction_annihilation_mastery",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "destruction_efficient_ruin" },
            cost = 2,
            x = 0,
            y = 560,
            title = "Annihilation Mastery",
            description = "Each elemental hit leaves the target raw to that element, stacking a brief weakness to fire, frost or shock with every strike.",
        },
    },
}
