return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "destruction_elemental_focus",
            tab = "Destruction",
            tabDescription = "Destruction skill governs spells that harm, corrode, or weaken enemies with fire, frost, shock, poison, and raw damage.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Elemental Focus",
            description = "Placeholder: Destruction spells gain a small reliability or damage bonus.",
        },
        {
            id = "destruction_searing_heat",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Searing Heat",
            description = "Placeholder: Fire damage spells apply an additional burning effect.",
        },
        {
            id = "destruction_biting_cold",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Biting Cold",
            description = "Placeholder: Frost damage spells slow or fatigue enemies.",
        },
        {
            id = "destruction_storm_channel",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "destruction_elemental_focus" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Storm Channel",
            description = "Placeholder: Shock damage spells disrupt enemy magicka or casting.",
        },
        {
            id = "destruction_corrosive_force",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 60,
            requires = {},
            requiresAny = { "destruction_searing_heat", "destruction_biting_cold", "destruction_storm_channel" },
            cost = 1,
            x = 0,
            y = 300,
            title = "Corrosive Force",
            description = "Placeholder: Weakness and damage-over-time Destruction effects become stronger.",
        },
        {
            id = "destruction_annihilation_mastery",
            tab = "Destruction",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "destruction_corrosive_force" },
            cost = 2,
            x = 0,
            y = 460,
            title = "Annihilation Mastery",
            description = "Placeholder: Master-level Destruction spells gain a significant finishing or efficiency bonus.",
        },
    },
}
