return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "heavyarmor_locked_frame",
            tab = "Heavy Armor",
            tabDescription = "Heavy Armor skill helps one endure punishment and hold ground in the heaviest protective gear.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -260,
            y = 0,
            title = "Heavy Skin",
            description = "While wearing a Heavy Armor cuirass, gain +2 Armor Rating for every complete 10 points of Heavy Armor skill.",
        },
        {
            id = "heavyarmor_iron_tread",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "heavyarmor_locked_frame" },
            cost = 1,
            x = -40,
            y = 115,
            title = "Iron Tread",
            description = "If you can wear boots, equipped Heavy Armor boots count as only half their weight for encumbrance. Argonian and Khajiit characters instead gain +10 Speed while wearing Heavy Armor greaves.",
        },
        {
            id = "heavyarmor_shock_padding",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "heavyarmor_iron_tread" },
            cost = 1,
            x = -300,
            y = 255,
            title = "Shock Padding",
            description = "While wearing a Heavy Armor cuirass, successful attacks or spell casts activate Shock Padding for 3 seconds, fortifying Heavy Armor by 5. Retriggering refreshes the duration.",
        },
        {
            id = "heavyarmor_anvil_stance",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "heavyarmor_iron_tread" },
            cost = 1,
            x = 190,
            y = 315,
            title = "Anvil Stance",
            description = "While wearing a Heavy Armor cuirass, each successful incoming attack grants +3 Endurance and +3 Heavy Armor for 10 seconds, stacking up to five times. New stacks refresh all Anvil Stance durations.",
        },
        {
            id = "heavyarmor_dreadnought",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "heavyarmor_shock_padding" },
            cost = 2,
            x = -230,
            y = 520,
            title = "Dreadnought",
            description = "Upgrades Shock Padding: while it is active, it fortifies Heavy Armor by 10 instead of 5 and restores 20 Fatigue gradually over its 3-second duration.",
        },
        {
            id = "heavyarmor_juggernaut_charge",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "heavyarmor_anvil_stance" },
            cost = 2,
            x = 230,
            y = 520,
            title = "Juggernaut Stance",
            description = "While in combat and wearing a Heavy Armor cuirass, restore 2 Fatigue per second and gain +10 Strength.",
        },
    },
}
