return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "heavyarmor_locked_frame",
            tab = "Heavy Armor",
            tabDescription = "Heavy Armor skill helps one endure punishment and hold ground in the heaviest protective gear.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -260,
            y = 0,
            title = "Locked Frame",
            description = "Placeholder: while wearing a Heavy Armor cuirass and greaves, gain added stability against incoming blows.",
        },
        {
            id = "heavyarmor_iron_tread",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "heavyarmor_locked_frame" },
            cost = 1,
            x = -40,
            y = 115,
            title = "Iron Tread",
            description = "Placeholder: heavy boots help you keep footing and reduce the penalties of moving under load.",
        },
        {
            id = "heavyarmor_shock_padding",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "heavyarmor_iron_tread" },
            cost = 1,
            x = -300,
            y = 255,
            title = "Shock Padding",
            description = "Placeholder: layered plates dampen part of the force from weapon hits while you are fully armored.",
        },
        {
            id = "heavyarmor_anvil_stance",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "heavyarmor_iron_tread" },
            cost = 1,
            x = 190,
            y = 315,
            title = "Anvil Stance",
            description = "Placeholder: standing your ground in Heavy Armor builds defensive momentum during sustained combat.",
        },
        {
            id = "heavyarmor_dreadnought",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "heavyarmor_shock_padding" },
            cost = 2,
            x = -230,
            y = 520,
            title = "Dreadnought",
            description = "Placeholder capstone: specialize in becoming an immovable bulwark with exceptional protection in Heavy Armor.",
        },
        {
            id = "heavyarmor_juggernaut_charge",
            tab = "Heavy Armor",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "heavyarmor_anvil_stance" },
            cost = 2,
            x = 230,
            y = 520,
            title = "Juggernaut Charge",
            description = "Placeholder capstone: specialize in turning Heavy Armor mass into relentless forward pressure.",
        },
    },
}
