return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "enchant_attentive_enchanter",
            tab = "Enchant",
            tabDescription = "Enchant binds magic into objects: charging and recharging them, and crafting enchanted gear.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Attentive Enchanter",
            description = "Enchant skill progress is increased by a quarter.",
        },
        {
            id = "enchant_enchanters_reserve",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Enchanter's Reserve",
            description = "+25 maximum magicka.",
        },
        {
            id = "enchant_thrifty_channeling",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "enchant_attentive_enchanter" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Thrifty Channeling",
            description = "Casting from an enchanted item refunds a quarter of the charge spent.",
        },
        {
            id = "enchant_brand_of_the_maker",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = {},
            requiresAny = { "enchant_attentive_enchanter", "enchant_enchanters_reserve" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Brand of the Maker",
            description = "Strikes that trigger your weapon's enchantment also apply Weakness to Magicka 20 for 5 seconds. Does not stack.",
        },
        {
            id = "enchant_spare_vessel",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "enchant_enchanters_reserve" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Spare Vessel",
            description = "Recharging with a soul gem has a 50% chance to return the gem empty.",
        },
        {
            id = "enchant_practiced_binding",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "enchant_spare_vessel" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Practiced Binding",
            description = "+25 Enchant while enchanting an item.",
        },
        {
            id = "enchant_living_enchantment",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "enchant_thrifty_channeling" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Living Enchantment",
            description = "Equipped enchanted items regain charge equal to a tenth of your Enchant every 10 seconds.",
        },
        {
            id = "enchant_soul_fed_blade",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "enchant_brand_of_the_maker" },
            cost = 2,
            x = 0,
            y = 280,
            title = "Soul-Fed Blade",
            description = "Killing a foe with an enchanted weapon fully recharges all equipped enchanted items.",
        },
    },
}
