return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "enchant_attentive_enchanter",
            tab = "Enchant",
            tabDescription = "Enchant binds magic into objects: charging and recharging them, and crafting enchanted gear.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -220,
            y = 0,
            title = "Attentive Enchanter",
            description = "You learn from every enchantment you handle: Enchant skill progress is increased by a quarter.",
        },
        {
            id = "enchant_enchanters_reserve",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 220,
            y = 0,
            title = "Enchanter's Reserve",
            description = "You hold more power in reserve: your maximum magicka is increased by 25.",
        },
        {
            id = "enchant_thrifty_channeling",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "enchant_attentive_enchanter" },
            cost = 1,
            x = -220,
            y = 140,
            title = "Thrifty Channeling",
            description = "Casting from an enchanted item returns a quarter of the charge it spent.",
        },
        {
            id = "enchant_brand_of_the_maker",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = {},
            requiresAny = { "enchant_attentive_enchanter", "enchant_enchanters_reserve" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Brand of the Maker",
            description = "When a strike from your enchanted weapon sets off its enchantment, the target is also left weak to magicka for a few seconds, so what follows bites harder.",
        },
        {
            id = "enchant_spare_vessel",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "enchant_enchanters_reserve" },
            cost = 1,
            x = 220,
            y = 140,
            title = "Spare Vessel",
            description = "When you recharge an item with a soul gem, half the time the emptied gem is returned to you.",
        },
        {
            id = "enchant_living_enchantment",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "enchant_thrifty_channeling" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Living Enchantment",
            description = "Enchanted items you wear or wield regain charge over time: a tenth of your Enchant skill every ten seconds, each.",
        },
        {
            id = "enchant_soul_fed_blade",
            tab = "Enchant",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "enchant_brand_of_the_maker" },
            cost = 2,
            x = 0,
            y = 280,
            title = "Soul-Fed Blade",
            description = "Slaying a foe with an enchanted weapon feeds the weapon: it regains 6 charge for every level the foe had.",
        },
    },
}
