-- Demo Long Blade tree used to validate chain layout + panning.
-- These node ids match demo perks registered in scripts/SkillPerkSystem/test_perks.lua.

return {
    {
        id = "longblade_demo_root",
        skill = "longblade",
        title = "Long Blade Fundamentals",
        description = "Core stance training for all long blade techniques.",
        x = 0,
        y = 0,
        requires = {},
    },
    {
        id = "longblade_demo_precision",
        skill = "longblade",
        title = "Precision Cuts",
        description = "Improves spacing and tip-control for measured strikes.",
        x = -180,
        y = 120,
        requires = { "longblade_demo_root" },
    },
    {
        id = "longblade_demo_pressure",
        skill = "longblade",
        title = "Pressure Rhythm",
        description = "Keeps tempo through chained attacks.",
        x = 0,
        y = 120,
        requires = { "longblade_demo_root" },
    },
    {
        id = "longblade_demo_cleaving",
        skill = "longblade",
        title = "Cleaving Arc",
        description = "Adds broad sweeps to control space.",
        x = 180,
        y = 120,
        requires = { "longblade_demo_root" },
    },
    {
        id = "longblade_demo_duelist",
        skill = "longblade",
        title = "Duelist Finish",
        description = "Focused finishing sequence from precision line.",
        x = -120,
        y = 260,
        requires = { "longblade_demo_precision" },
    },
    {
        id = "longblade_demo_whirlwind",
        skill = "longblade",
        title = "Whirlwind Finish",
        description = "Momentum-based finish from cleaving line.",
        x = 120,
        y = 260,
        requires = { "longblade_demo_cleaving" },
    },
    {
        id = "longblade_demo_mastery",
        skill = "longblade",
        title = "Grandmaster Form",
        description = "Final chain node requiring both finishers and pressure control.",
        x = 0,
        y = 420,
        requires = { "longblade_demo_duelist", "longblade_demo_whirlwind", "longblade_demo_pressure" },
    },
}
