return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "speechcraft_attentive_ear",
            tab = "Speechcraft",
            tabDescription = "Speechcraft governs persuasion: admiring, intimidating, and talking your way through.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Attentive Ear",
            description = "Speechcraft skill progress is increased by a quarter.",
        },
        {
            id = "speechcraft_well_met",
            tab = "Speechcraft",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "speechcraft_attentive_ear" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Well-Met",
            description = "Your first conversation with any NPC counts as a successful persuasion.",
        },
        {
            id = "speechcraft_face_saving",
            tab = "Speechcraft",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "speechcraft_well_met" },
            cost = 1,
            x = 0,
            y = 280,
            title = "Face Saving",
            description = "A failed persuasion has a 25% chance to cost no disposition.",
        },
        {
            id = "speechcraft_smooth_recovery",
            tab = "Speechcraft",
            effectId = "demo_noop",
            minimumSkill = 75,
            requires = { "speechcraft_face_saving" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Smooth Recovery",
            description = "Face Saving's chance rises to 50%.",
        },
        {
            id = "speechcraft_silver_tongue",
            tab = "Speechcraft",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "speechcraft_smooth_recovery" },
            cost = 2,
            x = 0,
            y = 560,
            title = "Silver Tongue",
            description = "A successful persuasion fortifies Speechcraft by 10 for 60 seconds. Does not stack.",
        },
        {
            -- Hidden: Speechcraft major with Illusion or Mercantile as a
            -- class skill. No race.
            id = "speechcraft_retinue",
            tab = "Speechcraft",
            effectId = "demo_noop",
            minimumSkill = 60,
            requires = { "speechcraft_well_met" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Retinue",
            description = "In dialogue, an NPC at disposition 80 or higher can be asked to follow you. One follower at a time; ask again to dismiss. Guards and essential NPCs refuse.",
            hiddenUnless = {
                majorSkills = { "speechcraft" },
                classSkillsAny = { "illusion", "mercantile" },
                label = "Speechcraft as a major skill with Illusion or Mercantile as a class skill",
            },
        },
    },
}
