return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "acrobatics_sure_footing",
            tab = "Acrobatics",
            tabDescription = "Acrobatics governs jumping and landing, and rewards spending time off the ground.",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = -180,
            y = 0,
            title = "Sure Footing",
            description = "While standing on the ground carrying less than half your capacity, gain +5 Acrobatics and +5 Agility.",
        },
        {
            id = "acrobatics_coiled_legs",
            tab = "Acrobatics",
            minimumSkill = 20,
            effectId = "demo_noop",
            requires = {},
            cost = 1,
            x = 180,
            y = 0,
            title = "Coiled Legs",
            description = "While your fatigue is above 60%, gain +10 Acrobatics.",
        },
        {
            id = "acrobatics_air_control",
            tab = "Acrobatics",
            minimumSkill = 35,
            effectId = "demo_noop",
            requires = { "acrobatics_sure_footing", "acrobatics_coiled_legs" },
            cost = 1,
            x = 0,
            y = 140,
            title = "Air Control",
            description = "While airborne, gain +10 Acrobatics and +10 Agility.",
        },
        {
            id = "acrobatics_wall_runner",
            tab = "Acrobatics",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "acrobatics_air_control" },
            cost = 1,
            x = -220,
            y = 280,
            title = "Wall Runner",
            description = "Air Control instead grants +20 Acrobatics and +15 Agility.",
        },
        {
            id = "acrobatics_rooftop_runner",
            tab = "Acrobatics",
            minimumSkill = 50,
            effectId = "demo_noop",
            requires = { "acrobatics_air_control" },
            cost = 1,
            x = 220,
            y = 280,
            title = "Rooftop Runner",
            description = "Landing after a jump recovers 10% of your maximum fatigue. Cannot occur more than once every 10 seconds.",
        },
        {
            id = "acrobatics_featherfall",
            tab = "Acrobatics",
            minimumSkill = 70,
            effectId = "demo_noop",
            requires = { "acrobatics_wall_runner", "acrobatics_rooftop_runner" },
            cost = 1,
            x = 0,
            y = 420,
            title = "Featherfall",
            description = "While airborne, also gain +10 Speed, and Rooftop Runner recovers 20% of your maximum fatigue instead of 10%.",
        },
        {
            id = "acrobatics_weightless",
            tab = "Acrobatics",
            minimumSkill = 90,
            effectId = "demo_noop",
            requires = { "acrobatics_featherfall" },
            cost = 2,
            x = 0,
            y = 580,
            title = "Weightless",
            description = "Gain +15 Acrobatics at all times, and your airborne bonuses linger for 2 seconds after you land.",
        },
    },
}
