return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "marksman_ranged_fundamentals",
            tab = "Marksman",
            tabDescription = "Marksman skill allows one to use bows, crossbows, throwing stars, and throwing knives effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 0,
            y = 0,
            title = "Ranged Fundamentals",
            description = "Placeholder: Learn the basics of steady aim, careful release, and keeping distance from your target.",
        },
        {
            id = "marksman_eagle_eye",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "marksman_ranged_fundamentals" },
            cost = 1,
            x = -180,
            y = 120,
            title = "Eagle Eye",
            description = "Placeholder: Your practiced sight picture makes long-range shots feel more reliable.",
        },
        {
            id = "marksman_quick_nock",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "marksman_ranged_fundamentals" },
            cost = 1,
            x = 0,
            y = 120,
            title = "Quick Nock",
            description = "Placeholder: Smooth handling lets you prepare follow-up shots with less wasted motion.",
        },
        {
            id = "marksman_hunters_patience",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 30,
            requires = { "marksman_ranged_fundamentals" },
            cost = 1,
            x = 180,
            y = 120,
            title = "Hunter's Patience",
            description = "Placeholder: Waiting for the right moment rewards deliberate, well-placed opening shots.",
        },
        {
            id = "marksman_pinning_shot",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 60,
            requires = {},
            requiresAny = { "marksman_eagle_eye", "marksman_quick_nock" },
            cost = 1,
            x = -120,
            y = 260,
            title = "Pinning Shot",
            description = "Placeholder: Precise ranged hits are intended to hinder enemies before they can close the gap.",
        },
        {
            id = "marksman_trick_throw",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 60,
            requires = {},
            requiresAny = { "marksman_quick_nock", "marksman_hunters_patience" },
            cost = 1,
            x = 120,
            y = 260,
            title = "Trick Throw",
            description = "Placeholder: Thrown weapons and snap shots are planned to gain a specialty benefit here.",
        },
        {
            id = "marksman_deadeye_mastery",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = {},
            requiresAny = { "marksman_pinning_shot", "marksman_trick_throw" },
            cost = 2,
            x = 0,
            y = 420,
            title = "Deadeye Mastery",
            description = "Placeholder capstone: Master marksmen are intended to land devastating shots under ideal conditions.",
        },
    },
}
