return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "marksman_bow_fundamentals",
            tab = "Marksman",
            tabDescription = "Marksman skill allows one to use bows, crossbows, throwing stars, and throwing knives effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -180,
            y = 0,
            title = "Bow Fundamentals",
            description = "While a bow or crossbow is equipped, fortify Agility by 5. Bows draw 20% faster.",
        },
        {
            id = "marksman_steady_draw",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "marksman_bow_fundamentals" },
            cost = 1,
            x = -180,
            y = 140,
            title = "Steady Draw",
            description = "Holding a bow or crossbow attack steadily increases the next shot's Health damage by up to 30% after 4 seconds.",
        },
        {
            id = "marksman_pinning_shot",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "marksman_steady_draw" },
            cost = 1,
            x = -180,
            y = 280,
            title = "Pinning Shot",
            description = "Bow and crossbow hits reduce target Speed by 10 for 5 seconds, stacking up to 3 times.",
        },
        {
            id = "marksman_thrown_fundamentals",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 180,
            y = 0,
            title = "Serrated Throws",
            description = "Thrown weapon hits apply a stacking bleed, dealing 3 Health damage over 3 seconds per stack.",
        },
        {
            id = "marksman_quick_cast",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "marksman_thrown_fundamentals" },
            cost = 1,
            x = 180,
            y = 140,
            title = "Quick Cast",
            description = "Thrown weapon attack animations are 80% faster, letting you release knives, darts, and stars more quickly.",
        },
        {
            id = "marksman_trick_throw",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "marksman_quick_cast" },
            cost = 1,
            x = 180,
            y = 280,
            title = "Hemorrhaging Throws",
            description = "Serrated Throws bleeds last 5 seconds. Thrown weapon hits deal 1 bonus Health damage for each Serrated Throws bleed stack already on the target.",
        },
        {
            id = "marksman_deadeye_mastery",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = {},
            requiresAny = { "marksman_pinning_shot", "marksman_trick_throw" },
            cost = 2,
            x = 0,
            y = 440,
            title = "Deadeye Mastery",
            description = "Placeholder capstone: Master marksmen are intended to gain a powerful benefit after committing to either the bow or thrown weapon path.",
        },
    },
}
