return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "marksman_bow_fundamentals",
            tab = "Marksman",
            tabDescription = "Marksman skill allows one to use bows, crossbows, throwing stars, and throwing knives effectively.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -180,
            y = 0,
            title = "Bow Fundamentals",
            description = "Placeholder bow path: Improve basic bow and crossbow handling before specializing further.",
        },
        {
            id = "marksman_steady_draw",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "marksman_bow_fundamentals" },
            cost = 1,
            x = -180,
            y = 140,
            title = "Steady Draw",
            description = "Placeholder bow path: Reward patient aim and controlled releases with bows and crossbows.",
        },
        {
            id = "marksman_pinning_shot",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "marksman_steady_draw" },
            cost = 1,
            x = -180,
            y = 280,
            title = "Pinning Shot",
            description = "Placeholder bow path: Precise arrows and bolts are intended to hinder enemies before they can close the gap.",
        },
        {
            id = "marksman_thrown_fundamentals",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = 180,
            y = 0,
            title = "Serrated Throws",
            description = "Thrown weapon hits apply a stacking bleed, dealing 3 Health damage over 3 seconds per stack.",
        },
        {
            id = "marksman_quick_cast",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 40,
            requires = { "marksman_thrown_fundamentals" },
            cost = 1,
            x = 180,
            y = 140,
            title = "Quick Cast",
            description = "Placeholder thrown path: Fast hands are planned to make thrown weapons feel more responsive in close skirmishes.",
        },
        {
            id = "marksman_trick_throw",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 65,
            requires = { "marksman_quick_cast" },
            cost = 1,
            x = 180,
            y = 280,
            title = "Trick Throw",
            description = "Placeholder thrown path: Thrown weapons are intended to gain a specialty benefit for opportunistic ranged attacks.",
        },
        {
            id = "marksman_deadeye_mastery",
            tab = "Marksman",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = {},
            requiresAny = { "marksman_pinning_shot", "marksman_trick_throw" },
            cost = 2,
            x = 0,
            y = 440,
            title = "Deadeye Mastery",
            description = "Placeholder capstone: Master marksmen are intended to gain a powerful benefit after committing to either the bow or thrown weapon path.",
        },
    },
}
