return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "mediumarmor_balanced_fit",
            tab = "Medium Armor",
            tabDescription = "Medium Armor skill helps one balance reliable protection with practical mobility.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -300,
            y = 40,
            title = "Balanced Fit",
            description = "While wearing both a Medium Armor cuirass and Medium Armor greaves, fortify Athletics and Speed by 5.",
        },
        {
            id = "mediumarmor_layered_padding",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "mediumarmor_balanced_fit" },
            cost = 1,
            x = -60,
            y = 160,
            title = "Layered Padding",
            description = "Increase Armor Rating by 1 for each equipped piece of Medium Armor.",
        },
        {
            id = "mediumarmor_steady_guard",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "mediumarmor_layered_padding" },
            cost = 1,
            x = 220,
            y = 260,
            title = "Steady Guard",
            description = "When you are hit by an attack, fortify Medium Armor by 3 for 10 seconds. Stacks up to 5 times, and each new stack refreshes all stacks.",
        },
        {
            id = "mediumarmor_tempered_stride",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 70,
            requires = { "mediumarmor_steady_guard" },
            cost = 1,
            x = -180,
            y = 400,
            title = "Armored Poise",
            description = "While wearing a Medium Armor cuirass, gain the Armored Poise ability.",
        },
        {
            id = "mediumarmor_battle_ready",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "mediumarmor_tempered_stride" },
            cost = 2,
            x = 260,
            y = 540,
            title = "Battle Ready",
            description = "While wearing a Medium Armor cuirass and greaves with Fatigue above 70%, fortify Medium Armor by 20.",
        },
    },
}
