return {
    schema = "skillperks.vNext",
    perks = {
        {
            id = "mediumarmor_balanced_fit",
            tab = "Medium Armor",
            tabDescription = "Medium Armor skill helps one balance reliable protection with practical mobility.",
            effectId = "demo_noop",
            minimumSkill = 20,
            requires = {},
            cost = 1,
            x = -300,
            y = 40,
            title = "Balanced Fit",
            description = "Placeholder perk for the Medium Armor tree.",
        },
        {
            id = "mediumarmor_layered_padding",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 35,
            requires = { "mediumarmor_balanced_fit" },
            cost = 1,
            x = -60,
            y = 160,
            title = "Layered Padding",
            description = "Placeholder perk for the Medium Armor tree.",
        },
        {
            id = "mediumarmor_steady_guard",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 50,
            requires = { "mediumarmor_layered_padding" },
            cost = 1,
            x = 220,
            y = 260,
            title = "Steady Guard",
            description = "Placeholder perk for the Medium Armor tree.",
        },
        {
            id = "mediumarmor_tempered_stride",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 70,
            requires = { "mediumarmor_steady_guard" },
            cost = 1,
            x = -180,
            y = 400,
            title = "Tempered Stride",
            description = "Placeholder perk for the Medium Armor tree.",
        },
        {
            id = "mediumarmor_battle_ready",
            tab = "Medium Armor",
            effectId = "demo_noop",
            minimumSkill = 90,
            requires = { "mediumarmor_tempered_stride" },
            cost = 2,
            x = 260,
            y = 540,
            title = "Battle Ready",
            description = "Placeholder perk for the Medium Armor tree.",
        },
    },
}
